// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Traceability.Persistence.DbContexts;

#nullable disable

namespace Traceability.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410155324_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Traceability.Domain.ConsumedMaterials.Entities.ConsumedMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ConsumedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductionRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("SourceReferenceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProductionRunId");

                    b.ToTable("ConsumedMaterials", (string)null);
                });

            modelBuilder.Entity("Traceability.Domain.MaterialGenealogies.Entities.MaterialGenealogy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InputMaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputMaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductionRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RelationType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProductionRunId");

                    b.ToTable("MaterialGenealogies", (string)null);
                });

            modelBuilder.Entity("Traceability.Domain.ProducedMaterials.Entities.ProducedMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LotId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ProducedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QualityStatus")
                        .HasColumnType("int");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<int>("SubLotId")
                        .HasColumnType("int");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProductionRunId");

                    b.ToTable("ProducedMaterials", (string)null);
                });

            modelBuilder.Entity("Traceability.Domain.ProductionRuns.Entities.ProductionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProductionRuns", (string)null);
                });

            modelBuilder.Entity("Traceability.Domain.ConsumedMaterials.Entities.ConsumedMaterial", b =>
                {
                    b.HasOne("Traceability.Domain.ProductionRuns.Entities.ProductionRun", "ProductionRun")
                        .WithMany("ConsumedMaterials")
                        .HasForeignKey("ProductionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionRun");
                });

            modelBuilder.Entity("Traceability.Domain.MaterialGenealogies.Entities.MaterialGenealogy", b =>
                {
                    b.HasOne("Traceability.Domain.ProductionRuns.Entities.ProductionRun", "ProductionRun")
                        .WithMany("MaterialGenealogies")
                        .HasForeignKey("ProductionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionRun");
                });

            modelBuilder.Entity("Traceability.Domain.ProducedMaterials.Entities.ProducedMaterial", b =>
                {
                    b.HasOne("Traceability.Domain.ProductionRuns.Entities.ProductionRun", "ProductionRun")
                        .WithMany("ProducedMaterials")
                        .HasForeignKey("ProductionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionRun");
                });

            modelBuilder.Entity("Traceability.Domain.ProductionRuns.Entities.ProductionRun", b =>
                {
                    b.Navigation("ConsumedMaterials");

                    b.Navigation("MaterialGenealogies");

                    b.Navigation("ProducedMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
